
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 10 03:26:43 CST 2020
//----------------------------------------------------

package proyectofinal.ctdoa.backend.analizador.visual_basic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSOLA = 4;
  public static final int NUMERO = 54;
  public static final int DISTINTO = 16;
  public static final int FUNCTION = 45;
  public static final int POR = 11;
  public static final int CHAR = 8;
  public static final int CASE = 43;
  public static final int INTEGER = 6;
  public static final int FOR = 36;
  public static final int FINPUT = 52;
  public static final int NOT = 21;
  public static final int AND = 22;
  public static final int ELSEIF = 40;
  public static final int IGUAL = 14;
  public static final int CARACTER = 3;
  public static final int OR = 23;
  public static final int DIV = 12;
  public static final int UNTIL = 32;
  public static final int SELECT = 42;
  public static final int NEXT = 37;
  public static final int LOOP = 33;
  public static final int IF = 38;
  public static final int AMPERSAND = 24;
  public static final int ID = 56;
  public static final int DIM = 26;
  public static final int EOF = 0;
  public static final int DECIMAL = 7;
  public static final int RETURN = 29;
  public static final int BYVAL = 25;
  public static final int error = 1;
  public static final int COMA = 50;
  public static final int CADENA = 2;
  public static final int COMENTARIO = 15;
  public static final int CONSOLA_LINEA = 5;
  public static final int MODULO = 13;
  public static final int MENOS = 10;
  public static final int MENOR = 17;
  public static final int REAL = 55;
  public static final int MAYOR = 18;
  public static final int CINPUT = 53;
  public static final int ELSE = 41;
  public static final int PARENTESIS_C = 48;
  public static final int TO = 34;
  public static final int WHILE = 30;
  public static final int PARENTESIS_A = 47;
  public static final int MAYOR_IGUAL = 20;
  public static final int PUBLIC = 44;
  public static final int THEN = 39;
  public static final int IINPUT = 51;
  public static final int END = 28;
  public static final int MENOR_IGUAL = 19;
  public static final int AS = 27;
  public static final int SALTO = 49;
  public static final int SUB = 46;
  public static final int DO = 31;
  public static final int STEP = 35;
  public static final int MAS = 9;
}

